site_name: WoltLab Suite Documentation
theme:
    name: material
    language: en
    custom_dir: overrides
    logo: assets/logo.png
    favicon: assets/default.favicon.ico
copyright: Copyright © 2020 WoltLab GmbH

nav:
    - 'Getting Started': 'getting-started_quick-start.md'

    - 'PHP API':
        - 'Pages': 'php_pages.md'
        - 'Database Objects': 'php_database-objects.md'
        - 'Database Access': 'php_database-access.md'
        - 'Exceptions': 'php_exceptions.md'
        - 'API':
            - 'Caches': 'php_api_caches.md'
            - 'Comments': 'php_api_comments.md'
            - 'Cronjobs': 'php_api_cronjobs.md'
            - 'Events': 'php_api_events.md'
            - 'Form Builder': 'php_api_form_builder.md'
            - 'Package Installation Plugins': 'php_api_package_installation_plugins.md'
            - 'User Activity Points': 'php_api_user_activity_points.md'
            - 'User Notifications': 'php_api_user_notifications.md'
            - 'Sitemaps': 'php_api_sitemaps.md'
        - 'Code Style': 'php_code-style.md'
        - 'Apps': 'php_apps.md'
        - 'GDPR': 'php_gdpr.md'

    - 'Languages, Templates & CSS':
        - 'Languages': 'view_languages.md'
        - 'Templates': 'view_templates.md'
        - 'CSS': 'view_css.md'

    - 'JavaScript API':
        - 'New API':
            - 'General Usage': 'javascript_general-usage.md'
            - 'Writing a module': 'javascript_new-api_writing-a-module.md'
            - 'Data Structures': 'javascript_new-api_data-structures.md'
            - 'Core Functions': 'javascript_new-api_core.md'
            - 'DOM': 'javascript_new-api_dom.md'
            - 'Event Handling': 'javascript_new-api_events.md'
            - 'Ajax': 'javascript_new-api_ajax.md'
            - 'Dialogs': 'javascript_new-api_dialogs.md'
            - 'Browser and Screen Sizes': 'javascript_new-api_browser.md'
            - 'User Interface': 'javascript_new-api_ui.md'
        - 'Legacy API': 'javascript_legacy-api.md'
        - 'Helper Functions': 'javascript_helper-functions.md'
        - 'Code Snippets': 'javascript_code-snippets.md'

    - 'Package Components':
        - 'package.xml': 'package_package-xml.md'
        - 'PIPs': 'package_pip.md'

    - 'Migration':
        - 'Migrating from WSC 5.2':
            - 'PHP API': 'migration_wsc-52_php.md'
            - 'Templates and Languages': 'migration_wsc-52_templates.md'
            - 'Third Party Libraries': 'migration_wsc-52_libraries.md'
        - 'Migrating from WSC 3.1':
            - 'PHP API': 'migration_wsc-31_php.md'
        - 'Migrating from WSC 3.0':
            - 'PHP API': 'migration_wsc-30_php.md'
            - 'JavaScript API': 'migration_wsc-30_javascript.md'
            - 'Templates': 'migration_wsc-30_templates.md'
            - 'CSS': 'migration_wsc-30_css.md'
            - 'Package Components': 'migration_wsc-30_package.md'
        - 'Migrating from WCF 2.1':
            - 'PHP API': 'migration_wcf-21_php.md'
            - 'Templates': 'migration_wcf-21_templates.md'
            - 'CSS': 'migration_wcf-21_css.md'
            - 'Package Components': 'migration_wcf-21_package.md'

    - 'Tutorials':
        - 'Tutorial Series': 'tutorial_tutorial-series.md'

markdown_extensions:
    - toc:
        permalink: "#"
        toc_depth: 2
    - admonition
    - abbr
    - pymdownx.highlight
    - pymdownx.superfences

extra_css:
    - stylesheets/extra.css
