site_name: WoltLab Suite Documentation
theme:
  name: material
  language: en
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/default.favicon.ico
copyright: Copyright © 2020 WoltLab GmbH

nav:
  - 'Getting Started': 'getting-started.md'

  - 'PHP API':
    - 'Pages': 'php/pages.md'
    - 'Database Objects': 'php/database-objects.md'
    - 'Database Access': 'php/database-access.md'
    - 'Exceptions': 'php/exceptions.md'
    - 'API':
      - 'Caches': 'php/api/caches.md'
      - 'Comments': 'php/api/comments.md'
      - 'Cronjobs': 'php/api/cronjobs.md'
      - 'Events': 'php/api/events.md'
      - 'Form Builder': 'php/api/form_builder.md'
      - 'Package Installation Plugins': 'php/api/package_installation_plugins.md'
      - 'User Activity Points': 'php/api/user_activity_points.md'
      - 'User Notifications': 'php/api/user_notifications.md'
      - 'Sitemaps': 'php/api/sitemaps.md'
    - 'Code Style': 'php/code-style.md'
    - 'Apps': 'php/apps.md'
    - 'GDPR': 'php/gdpr.md'

  - 'Languages, Templates & CSS':
    - 'Languages': 'view/languages.md'
    - 'Templates': 'view/templates.md'
    - 'CSS': 'view/css.md'

  - 'JavaScript API':
    - 'General Usage': 'javascript/general-usage.md'
    - 'New API':
      - 'Writing a module': 'javascript/new-api_writing-a-module.md'
      - 'Data Structures': 'javascript/new-api_data-structures.md'
      - 'Core Functions': 'javascript/new-api_core.md'
      - 'DOM': 'javascript/new-api_dom.md'
      - 'Event Handling': 'javascript/new-api_events.md'
      - 'Ajax': 'javascript/new-api_ajax.md'
      - 'Dialogs': 'javascript/new-api_dialogs.md'
      - 'Browser and Screen Sizes': 'javascript/new-api_browser.md'
      - 'User Interface': 'javascript/new-api_ui.md'
    - 'Legacy API': 'javascript/legacy-api.md'
    - 'Helper Functions': 'javascript/helper-functions.md'
    - 'Code Snippets': 'javascript/code-snippets.md'

  - 'Package Components':
    - 'package.xml': 'package/package-xml.md'
    - 'PIPs': 'package/pip.md'

  - 'Migration':
    - 'Migrating from WSC 5.3':
      - 'PHP API': 'migration/wsc53/php.md'
      - 'Session Handling and Authentication': 'migration/wsc53/session.md'
      - 'JavaScript': 'migration/wsc53/javascript.md'
      - 'Templates': 'migration/wsc53/templates.md'
      - 'Third Party Libraries': 'migration/wsc53/libraries.md'
    - 'Migrating from WSC 5.2':
      - 'PHP API': 'migration/wsc52/php.md'
      - 'Templates and Languages': 'migration/wsc52/templates.md'
      - 'Third Party Libraries': 'migration/wsc52/libraries.md'
    - 'Migrating from WSC 3.1':
      - 'PHP API': 'migration/wsc31/php.md'
    - 'Migrating from WSC 3.0':
      - 'PHP API': 'migration/wsc30/php.md'
      - 'JavaScript API': 'migration/wsc30/javascript.md'
      - 'Templates': 'migration/wsc30/templates.md'
      - 'CSS': 'migration/wsc30/css.md'
      - 'Package Components': 'migration/wsc30/package.md'
    - 'Migrating from WCF 2.1':
      - 'PHP API': 'migration/wcf21/php.md'
      - 'Templates': 'migration/wcf21/templates.md'
      - 'CSS': 'migration/wcf21/css.md'
      - 'Package Components': 'migration/wcf21/package.md'

  - 'Tutorials':
    - 'Tutorial Series': 'tutorial/series/overview.md'

markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 4
  - admonition
  - abbr
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: "snippets/"

extra_css:
  - stylesheets/extra.css
