name: Test

on:
  push:
    branches-ignore:
    - 'gh-pages'
    - 'target'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip3 install -r requirements.txt
    - run: mkdocs build
